### ISSUE TITLE
[Design kit]: Update masthead L1 interactive states

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-dotcom-library-design-kit#37]
As a designer, I need access to accurate Sketch files, so my designs match was is available in code

**Tasks**
- update hover, focus, selected states for the L1 based on the latest designs
- cover all scenarios: with and without back link for L1 title chip
- write release notes

**Acceptance criteria**
- [ ] Reviewed by design [Lara]
- [ ] New file uploaded to design kit folder
- [ ] Release notes documented
